[package]
name = "slack"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
# Local
common.workspace = true

anyhow.workspace = true
lambda_http.workspace = true
slack-morphism.workspace = true
serde_json.workspace = true
