[tasks.format]
install_crate = "rustfmt"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.watch]
command = "cargo"
args = ["watch"]
dependencies = ["format"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]
