[package]
name = "s3-helper"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
aws-sdk-s3.workspace = true
regex.workspace = true
reqwest.workspace = true
thiserror.workspace = true
url.workspace = true
urlencoding.workspace = true
